FROM scratch
MAINTAINER Gianmauro Cuccuru <gmauro@gmail.com>
LABEL architecture="ARMv7l"


# Mini Root Filesystem
#https://nl.alpinelinux.org/alpine/v3.5/releases/armhf/alpine-minirootfs-3.5.2-armhf.tar.gz
ADD alpine-minirootfs-3.5.2-armhf.tar.gz /

CMD ["/bin/sh"]